namespace Illusion.Formats.Translokator;

// Vendored from MafiaToolkit (ActorEnums.cs) — only the ActorTypes enum is needed by the
// Translokator reader (ObjectGroup.ActorType). Casting unknown ids to the enum is harmless.
public enum ActorTypes
{
    None = 0,
    Human = 14,
    C_Player2 = 16,
    C_Car = 18,
    C_Train = 19,
    C_CrashObject = 20,
    C_TrafficCar = 21,
    C_TrafficHuman = 22,
    C_TrafficTrain = 23,
    ActionPoint = 25,
    ActionPointScript = 30,
    ActionPointSearch = 32,
    C_Item = 36,
    C_Door = 38,
    Tree = 39,
    Lift = 40,
    C_Sound = 41,
    SoundMixer = 43,
    Boat = 47,
    Radio = 48,
    JukeBox = 49,
    StaticEntity = 52,
    C_TranslocatedCar = 53,
    Garage = 54,
    FrameWrapper = 55,
    C_ActorDetector = 56,
    Blocker = 63,
    C_StaticWeapon = 64,
    C_StaticParticle = 66,
    FireTarget = 70,
    LightEntity = 71,
    C_Cutscene = 73,
    Telephone = 95,
    C_ScriptEntity = 98,
    DangerZone = 103,
    Airplane = 104,
    C_Pinup = 106,
    SpikeStrip = 107,
    C_DummyDoor = 109,
    FramesController = 110,
    Wardrobe = 112,
    PhysicsScene = 113,
    CleanEntity = 114
}
